version: '3'
services:

  #Python
  python:
    image: python:latest
    container_name: python_saana
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./../:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
    networks:
      - mynet
 #Nginx Service
  nginx:
    image: nginx:latest
    container_name: nginx_saana
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./../:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
    networks:
      - mynet
  #AngularApp
  angular:
    image: node:latest
    container_name: angular_saana
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "443:443"
    tty: true
      environment:
        SERVICE_NAME: app
        SERVICE_TAGS: dev
      working_dir: /var/www/html
      volumes:
        - ./../:/var/www/html
      networks:
        - mynet
  #Mongo
  mongo:
    image: mongo
    container_name: mongo_saana
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  #Docker Networks
  networks:
    mynet:
      driver: bridge
  #Volumes
  volumes:
    mysqldata:
      driver: local
